// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pitdhkkrzxbkwqfzrhyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpdGRoa2tyenhia3dxZnpyaHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzY2ODEsImV4cCI6MjA3MDY1MjY4MX0.WTpGkE9bh5IUpD3tQYx58gWeXZTQstnlMVHcl3HQdfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});